### ISSUE TITLE
Is there plan to support cmake compile?

### ISSUE THREAD

**Issue by yilun-zhangs** [AOMediaCodec/iamf-tools#12]
@jwcullen 
Currently, the project is compiled by bazel, is there plan to support cmake compile?

**Comment by jwcullen** [comment]
Nothing immediately is planned. It ends up being extra maintenance to support multiple build systems.

If we had it, then it would be nice if it had feature parity with the bazel builds. The existing build works on Linux, Mac, Windows. It builds with Clang or GCC. It also grabs and builds specific versions of library dependencies from source.

I know this all possible with cmake, but it's not priority to research and implement the correct and modern way to do all of these things. Especially in a way that makes it easily maintainable and ideally not have to be messed with very often.
