### ISSUE TITLE
Support Native MacOS Build

### ISSUE THREAD

**Issue by BrandenAvalonCx** [AOMediaCodec/iamf-tools#8]
Currently this project may not build on MacOs / ARM.

Looks like the cause is missing ARM header files and missing include directories on some of the dependencies in Bazel. Updated the build script accordingly.

Opened a PR to fix here: https://github.com/AOMediaCodec/iamf-tools/pull/7

Let me know if you need anything else to review / merge.

**Comment by jwcullen** [comment]
Let's add a `macos-latest` target to the GitHub Actions CI before closing this bug.

**Comment by jwcullen** [comment]
MacOS Clang does not support [Parenthesized initialization of aggregates](https://en.cppreference.com/w/cpp/compiler_support/20)" which may break building some tests on certain MacOS configurations.

**Comment by jwcullen** [comment]
We now have CI [macos-latest](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) which builds and passes all unit tests.

@BrandenAvalonCx (or future readers), please re-open or file further issues if you have any problems building on MacOS.
